### ISSUE TITLE
Purchase callback

### ISSUE THREAD

**Issue by i-schuetz** [serso/android-checkout#104]
I was wondering why it's not possible to pass a callback directly to `purchase` and this has to be done via flow instead, which has to be stored as instance variable?

The reason I ask is that I'm creating a common interface for this lib and the "trivial drive" implementation, and it would be very handy if `purchase` could just have a callback that can be passed directly to this method (or instantiated in the same place) instead of having to wait for the result in another place.

An immediate solution would be to initialize a purchase flow with a new listener inside my purchase method, but I don't know if this is a good idea, considering that in the example this is done only once in the activity's `onCreate`...

**Comment by serso** [comment]
@i-schuetz I don't really understand your suggestion. `PurchaseFlow` class was created in order to manage quite complex "purchase flow", including handling a callback from the billing API and a response sent via `onActivityResult`.
Now you don't have to create a flow in `onCreate` method but you can do this only when needed, for example in `onClickListener` of "Buy" button. However, the flow object should be stored somewhere (now it is done in `UiCheckout` class) due to the reasons explained above.
