### ISSUE TITLE
onSuccess() is not triggered within PurchaseListener

### ISSUE THREAD

**Issue by matinzk** [serso/android-checkout#124]
I am testing my app "android.test.refunded" and "android.test.purchased" but onSuccess is never triggered.

The error I get within PurchaseListener is:
```
org.solovyev.android.checkout.Check$AssertionException: Object should not be null
```
Any suggestions?

**Comment by serso** [comment]
That's a known problem with these static responses. They for some reason don't include all the required information. In this case if I recall correctly the signature is missing. You can submit a bug report in Google bug tracker but I doubt you'll get any answer: https://issuetracker.google.com/issues/new?component=311487&template=1014446

**Comment by LiviuSebastian** [comment]
I think I might found a possible explanation for this while encountering the same problem: onSuccess() not being called. First of all I have to say that I am a beginner Android developer. So you may find stupid what I am going to say.  

In my case onSuccess() was not being called because of two possible causes:

1.  the activity from within I was calling all "Checkout" methods was declared with "android:noHistory="true"" in manifest. Acording to [https://developer.android.com/reference/android/app/Activity.html#startActivityForResult(android.content.Intent, int, android.os.Bundle)](url)

in activities that were declared with noHistory="true",    onActivityResult() is never invoked.  That also means that onSuccess() is never invoked too.

2. Second problem was that the activity from within I was calling all "Checkout" methods was started from within a ServiceIntent with the help of Context.startActivity(Intent).  BUT starting activities with "startActivity(Intent)" does not trigger  onActivityResult() in the started activity. That also means that onSuccess() is never invoked too. You have to use Activity.startActivityForResult(Intent, int); for onActivityResult() to be called.

So deleting the "noHistory = true" from the declaration of activity in manifest and starting the activity that "connects" to Checkout from within another activity using Activity.startActivityForResult(Intent, int); instead of  startActivity(Intent) solved my problem.

It took me 3 days to solvit.

Hopefully now I will be able to launch my app on play store.

@serso Thank you for the Checkout library. Great Work!

Please let me know if the problems that I found did helped others too!

**Comment by ihorvlasyuk** [comment]
Any other ideas how to solve this issue? I need these callbacks for some actions

**Comment by ihorvlasyuk** [comment]
Can't get these events for subscriptions.

**Comment by T-igra** [comment]
I solved this problem with static responses. It would be nice to add support for static  responses to the library. The error occurs in the default PurchaseVerifier for the signature, which in this case is null.

1. override **getPurchaseVerifier**() in CheckoutApplication for Billing.DefaultConfiguration()
https://github.com/serso/android-checkout/blob/bb989bfeca8f461f9388b35d266f5c5677222bc8/app/src/main/java/org/solovyev/android/checkout/app/CheckoutApplication.java
```
mBilling = new Billing(context, new Billing.DefaultConfiguration() {
	...
	@Nonnull
	@Override
	public PurchaseVerifier getPurchaseVerifier() {
		return new MyPurchaseVerifier(getPublicKey());
	}
});
```
2. add your own PurchaseVerifier
```
class MyPurchaseVerifier implements PurchaseVerifier {
	@Nonnull
	private final String mPublicKey;

	public MyPurchaseVerifier(@Nonnull String publicKey) {
		mPublicKey = publicKey;
	}

	@Override
	public void verify(@Nonnull List<Purchase> purchases, @Nonnull RequestListener<List<Purchase>> listener) {
		final List<Purchase> verifiedPurchases = new ArrayList<Purchase>(purchases.size());
		for (Purchase purchase : purchases) {
			if ("android.test.purchased;android.test.canceled;android.test.refunded;android.test.item_unavailable".contains(purchase.sku)) {
				verifiedPurchases.add(purchase);
			} else if (Security.verifyPurchase(mPublicKey, purchase.data, purchase.signature)) {
				verifiedPurchases.add(purchase);
			} else {
				if (isEmpty(purchase.signature)) {
				    // Log.e(this.getClass().toString(), "Cannot verify purchase: " + purchase + ". Signature is empty");
				} else {
				    // Log.e(this.getClass().toString(), "Cannot verify purchase: " + purchase + ". Wrong signature");
				}
			}
		}
		listener.onSuccess(verifiedPurchases);
	}
}
```
3. copy org.solovyev.android.checkout.Security class to your package because org.solovyev.android.checkout.Security is not public and cannot be accessed from outside package.

That's all. "android.test.*" static responses now start working correctly with onSuccess event.

**Comment by Tiggs777** [comment]
Thanks @T-igra ur solution helped me resolve purchase verification issue.

**Comment by Delilovic** [comment]
After 5 days of trying every option (debugging and release billing) I just realized that I forgot to add

@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        mCheckout.onActivityResult(requestCode, resultCode, data);
    }

to my activity. 

@T-igra Your comment helped me to realize that. I was first thinking "why does he speak about android intern onActivityResult that has nothing to do with this"....how wrong I was :D 

Hope this helps someone searching for this issue.
