### ISSUE TITLE
Consume purchase on app start

### ISSUE THREAD

**Issue by blood73** [serso/android-checkout#127]
I have the InApp which should be always available for purchase. Something like the one life in the game. So, I realised the logic for purchase this item and then consume this item after a purchase. But, it it possible to consume this InApp after the app starts? For example, user applied a promocode in the Google Play. I can check on an app start if the InApp isPurchased, but how to consume the InApp on the app start without start a purchase flow?

**Comment by blood73** [comment]
I have this code now:

```
if (product.isPurchased(MILEAGE_1)) {
                increaseInAppCount(1);
                Purchase purchase1 = product.getPurchaseInState(MILEAGE_1, Purchase.State.PURCHASED);
                if (purchase1 != null) {
                    consume(purchase1);
                }
            }

    private void consume(final Purchase purchase) {
        mCheckout.whenReady(new Checkout.EmptyListener() {
            @Override
            public void onReady(@Nonnull BillingRequests requests) {
                requests.consume(purchase.token, makeRequestListener());
            }
        });
    }

    private <T> RequestListener<T> makeRequestListener() {
        return new RequestListener<T>() {
            @Override
            public void onSuccess(@Nonnull T result) {
                logD(TAG, "success consume");
            }

            @Override
            public void onError(int response, @Nonnull Exception e) {
                logD(TAG, "error consume");
            }
        };
    }
```

But this doesn't consume a product. On every app run this line of code run: increaseInAppCount(1); But consume doesn't work

**Comment by serso** [comment]
There shouldn't be any difference in when or where a "consume" request is sent. If you check out the sample app you can verify that the purchased items can be consumed at any time.
This gives us two possibilities: 
1. Either there is an error in your code (there isn't from what I see) or in your setup (PK/account/release APK)
2. Or Google Play doesn't support it

What error code do you receive from the billing API in `RequestListener#onError`?

**Comment by serso** [comment]
@blood73 is `purchase#token` not empty?
Also, do you test on a released (alpha/beta/final) version of the app?

**Comment by blood73** [comment]
I can't say about token now. I tested this on alpha version

6 нояб. 2017 г. 13:20 пользователь "Sergey Solovyev" <
notifications@github.com> написал:

@blood73 <https://github.com/blood73> is purchase#token not empty?
Also, do you test on a released (alpha/beta/final) version of the app?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/serso/android-checkout/issues/127#issuecomment-342090181>,
or mute the thread

**Comment by hughpearse** [comment]
Bump
I am using org.solovyev.android:checkout:1.2.1 so that my application can use targetSdkVersion 23.  This allows it to support devices starting from android v6.

When I purchase a product (sucessfully):
DonateActivity: Button5 was pressed, mCheckout is ready
DonateActivity: Purchase failed.
DonateActivity: Response 10001
DonateActivity: Exception java.lang.IllegalArgumentException: org.solovyev.android.checkout.Base64DecoderException: Bad Base64 input character at 15: 44(decimal)

When I query the customers inventory:
DonateActivity: Reloading customers inventory
DonateActivity: 0 skus (sub)
DonateActivity: 4 skus (inapp)
DonateActivity: Sku donate_10_euro has 0 purchases
DonateActivity: Sku donate_15_euro has 0 purchases
DonateActivity: Sku donate_1_euro has 0 purchases
DonateActivity: Sku donate_5_euro has 0 purchases

Whatever fixes may have been introduced in to newer versions of the library may need to be patched on to previous releases.

My project
https://github.com/hughpearse/androidtexttospeechereader/blob/master/app/src/main/java/hughpearse/myapplication004/DonateActivity.java

**Comment by serso** [comment]
@hughpearse your issue has nothing to do with this. Please don't post the same message in several threads. In your case you don't provide a valid Base64 encoded public key. Please refer to the documentation.
