### ISSUE TITLE
How can i cancel a subscription?

### ISSUE THREAD

**Issue by xellent1** [serso/android-checkout#166]
Hello everybody, i have bought a subscription in my app
requests.purchase(ProductTypes.SUBSCRIPTION, P_PREMIUM_ACCOUNT, null, mCheckout.getPurchaseFlow());

but i can't found a method which cancels my subscription. Help me please.
I have lost a plenty of time, looking for definite answer, but i failed

**Comment by mikejeep** [comment]
Trigger the same routine again. Google Play will display options for subscriptions that are active.

**Comment by Johnson145** [comment]
According to the [linked article on Medium](https://android.jlelse.eu/implementing-in-app-billing-in-android-4896232c7d6b), this library does not support the cancellation of subscriptions from within the app. The article states that it's not possible, because the underlaying Google APIs do not provide such a feature. The latter information seems to be outdated, [as the official Android documentation](https://developer.android.com/google/play/billing/billing_subscriptions.html#Cancel) now describes such a feature. 

So this library may need to get updated to natively support subscription cancelling.

[mikejeep's answer](https://github.com/serso/android-checkout/issues/166#issuecomment-503286247) looks like an interesting workaround though.

**Comment by serso** [comment]
I still don't think it's possible to programmatically cancel a subscription - there is simply no method for doing that in the Billing API.
Documentation mentioned by @Johnson145 says:
> A user can also cancel a subscription from the Play Store app. Using the Google Play Developer API, you can also cancel a subscription using Purchases.subscriptions:cancel.
The first sentence is about manually cancelling a subscription via Play Store app. The second is about using Google Play Developer API which is **not** the same as the Billing API.
