### ISSUE TITLE
Account Hold /  SUBSCRIPTION_ON_HOLD

### ISSUE THREAD

**Issue by Johnson145** [serso/android-checkout#171]
Does this library handle the [subscription on hold](https://developer.android.com/google/play/billing/billing_subscriptions.html#on_hold) state? If so, how does it behave? Does it automatically (in)validate the associated purchases? Or do I need to take action on this state?

I couldn't find anything about it in this repository. Hoping I don't miss anything obvious. Thanks in advance!

**Comment by schleichmichel** [comment]
Since account hold (and restore) must be supported by November 1 ([source](https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html)), are there any news on this matter?

**Comment by benj9000** [comment]
> Since account hold (and restore) must be supported by November 1 ([source](https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html)), are there any news on this matter?

Since November 1 passed, my conclusions are as follows:

This library uses [Google Play's billing system with AIDL](https://developer.android.com/google/play/billing/api.html), which btw will not work after August/November 2021 for new apps/updates [(Source)](https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html). Everything regarding status "happens at Google Play" (if we do not maintain a backend server for managing subscriptions) and only the information whether a subscription is active or not is delivered to the app via the API. I.e. we will not have to care about those status in-app, if we do not use such a backend server.
