### ISSUE TITLE
Is this BL still supported? 

### ISSUE THREAD

**Issue by mladenbabic** [serso/android-checkout#176]
I have seen many questions and no answers to them, so is this library still supported by the author? We need it for the next BL 3 version.

Kind regards,
Mladen

**Comment by akshaaatt** [comment]
I have made an Android Library to manage Google Play Billing, In App Purchases and Subscriptions with just a few lines of code.
Check it out and be sure to star the project if you liked my contribution :)

https://github.com/akshaaatt/Google-IAP

**Comment by mikejeep** [comment]
Adding polite a "me too" to this issue, as I hope this library could be updated to support current requirements. Google has set deadlines to migrate to Google Play Billing Library version 3, and in a few months app updates will be rejected.

**Comment by willadmin78** [comment]
"me three"

**Comment by serso** [comment]
Hey all, the lib already supports Billing v7 https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/Billing.java#L74
I'm not sure I understand what is meant by "Google has set deadlines to migrate to Google Play Billing Library version 3".
I haven't worked much on the library itself lately because "it just works" in all my apps.
I don't plan to abandon the library. However, I don't plan to actively develop it either.
Said that public contributions are more than welcome, If you're missing a feature please add it and push a PR here on GitHub.
Thanks for using the lib!

**Comment by mikejeep** [comment]
@serso -- Google Play is mandating all apps use the latest version of the library; I believe I remember seeing a v2 .jar included with your library. My app receives warnings from Google Play because of it.

"Starting August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer."

Quote from here: https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html?m=1

**Comment by serso** [comment]
I didn't get any warning when releasing a new version of the sample app so the issue should be fixed in version 1.2.3. I've just published it and it will soon appear in Maven Central.
