### ISSUE TITLE
static In-app Billing Responses

### ISSUE THREAD

**Issue by elcolto** [serso/android-checkout#33]
Hi,
I'm using this library on a project.
I'm trying to test  purchases witht testing ids from Google (see here: http://developer.android.com/google/play/billing/billing_testing.html#billing-testing-static).

When I purchase a product with `requests.purchase(sku, null, checkout.getPurchaseFlow())`, I will always get a callback on `onError(int response, @Nonnull Exception e)` with a response code: `ResponseCodes.WRONG_SIGNATURE`.
Even when i try to use the testing ids with the sample app, the same issue occures. Do you have any suggestions how to test with these ids, or can you explain what this ResponseCode exactly mean?

**Comment by serso** [comment]
ResponseCodes.WRONG_SIGNATURE means that purchase can't be verified due to a wrong signature (according to PurchaseVerifier). You can tweak the default behavior by switching to a custom PurchaseVerifier (f.e. you can verify purchases on the remote server).
I think however that you face a known bug in Google In-App Billing API - static resonces can't be verified due to missing signature, see http://stackoverflow.com/a/22088718/720489 for more information. In order to workaround this you can disable verification by providing another implementation of PurchaseVerifier which just approves all purchases (don't forget to bring back the default implementation after testing is done).

**Comment by serso** [comment]
Do you have any further questions? Can I close the issue?

**Comment by elcolto** [comment]
Thank you, your Answer was really helpful!
I think you can close this "issue".

**Comment by csbenz** [comment]
I'm getting the 'wrong signature' error. How can I override getPurchaseVerifier with the latest version of Checkout? I tried but it doesn't seem possible. Thanks

**Comment by serso** [comment]
@csbenz you can sub-class `Billing.DefaultConfiguration` and override `getPurchaseVerifier` method.

**Comment by csbenz** [comment]
@serso great responsiveness, thanks. Your lib is great and I'm struggling to make it work correctly with BaseActivities and BaseFragments. Finally getting there. Thanks!
