### ISSUE TITLE
why are these proguard rules needed? 

### ISSUE THREAD

**Issue by ruoyul** [serso/android-checkout#40]
Hi, 

In the documentation you mentioned these proguard rules needs to be added: https://github.com/serso/android-checkout/blob/master/lib/proguard-rules.txt. 

Is there any reason to have the line: 
`-assumenosideeffects class org.solovyev.android.checkout.Check {
        *;
}`
?

I've found that if I include these lines it makes my (fairly large) android application run very slowly. Removing these lines makes the performance back to normal again. I'm wondering what these lines are doing and wether there would be any ill effects if I don't include them in my proguard.cfg?

Thanks in advance for your help!

**Comment by serso** [comment]
"Check" class is used instead of assertions (as assertions are not turned on by default in Android VM). Removing this class disables all checks in the library and is a good thing to do for release version of the app as it makes it smaller and faster (just a little bit). However, I don't think that this should dramatically  affect performance. Maybe it's some other proguard rules that do that?

**Comment by ruoyul** [comment]
Actually, I just found one SO article answered by the creator of proguard Eric Lafortune himeself. 

Basically we should never use assumenosideeffects with wildcard.
It's guaranteed to generate a disaster because it will remove wait, notify and notifyAll functions from every classes , not just the class you specified.
It will break the synchronization and make some threads busying waiting and consume lots of CPU cycles, causing performance degradation, battery drain and deadlocks.

Article:
http://stackoverflow.com/questions/16846691/proguard-ate-my-object-wait

Hope this helps.
Thanks!
