### ISSUE TITLE
Inventory.Callback doesn't have something like onError or onFailed?

### ISSUE THREAD

**Issue by dreasn** [serso/android-checkout#95]
In `Inventory.Callback` class  quite often I need to get notified if error happened. 
(currently only onLoaded available).

**Comment by serso** [comment]
Unfortunately due to the current library design it is difficult to add `onError` method to the `Inventory.Callback`. One way to check that the loading fails is through `Product#supported`. However, this field is not updated (and shouldn't be) if for example SKUs loading fails.

There is also `Billing#setLogger` that can be used to detect all errors that happen in `Billing`.
